// Code generated by Kitex v0.9.1. DO NOT EDIT.

package inventoryservice

import (
	"context"
	inventory "github.com/Yzc216/gomall/rpc_gen/kitex_gen/inventory"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	QueryStock(ctx context.Context, Req *inventory.QueryStockReq, callOptions ...callopt.Option) (r *inventory.QueryStockResp, err error)
	ReserveStock(ctx context.Context, Req *inventory.InventoryReq, callOptions ...callopt.Option) (r *inventory.InventoryResp, err error)
	ConfirmStock(ctx context.Context, Req *inventory.InventoryReq, callOptions ...callopt.Option) (r *inventory.InventoryResp, err error)
	ReleaseStock(ctx context.Context, Req *inventory.InventoryReq, callOptions ...callopt.Option) (r *inventory.InventoryResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kInventoryServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kInventoryServiceClient struct {
	*kClient
}

func (p *kInventoryServiceClient) QueryStock(ctx context.Context, Req *inventory.QueryStockReq, callOptions ...callopt.Option) (r *inventory.QueryStockResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.QueryStock(ctx, Req)
}

func (p *kInventoryServiceClient) ReserveStock(ctx context.Context, Req *inventory.InventoryReq, callOptions ...callopt.Option) (r *inventory.InventoryResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ReserveStock(ctx, Req)
}

func (p *kInventoryServiceClient) ConfirmStock(ctx context.Context, Req *inventory.InventoryReq, callOptions ...callopt.Option) (r *inventory.InventoryResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ConfirmStock(ctx, Req)
}

func (p *kInventoryServiceClient) ReleaseStock(ctx context.Context, Req *inventory.InventoryReq, callOptions ...callopt.Option) (r *inventory.InventoryResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ReleaseStock(ctx, Req)
}
