// Code generated by hertz generator.

package category

import (
	"github.com/Yzc216/gomall/app/frontend/middleware"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/hertz-contrib/casbin"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.JwtMiddleware.MiddlewareFunc(),
		// 1:管理员 2:普通用户 3:商家
		middleware.Casbinauth.RequiresRoles("1 2 3", casbin.WithLogic(casbin.OR), casbin.WithUnauthorized(middleware.UnAuthorization), casbin.WithForbidden(middleware.UnAuthorization)),
	}
}

func _categoryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _category0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createcategoryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listcategoryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _category1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createcategorypageMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _productMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _adminMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _categorymanagementMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatecategoryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletecategoryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getproductbycategoryidMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _category_idMw() []app.HandlerFunc {
	// your code...
	return nil
}
