// Code generated by hertz generator.

package auth

import (
	"github.com/Yzc216/gomall/app/frontend/middleware"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/hertz-contrib/casbin"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _authMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _loginMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.JwtMiddleware.MiddlewareFunc(),
		// 1:管理员 2:普通用户 3:商家
		middleware.Casbinauth.RequiresRoles("1 2 3", casbin.WithLogic(casbin.OR), casbin.WithUnauthorized(middleware.UnAuthorization), casbin.WithForbidden(middleware.UnAuthorization)),
	}
}

func _logoutMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _registerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _adminMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _user0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _admin0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _setroleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _banMw() []app.HandlerFunc {
	// your code...
	return nil
}
