// Code generated by hertz generator.

package auth

import (
	"github.com/Yzc216/gomall/app/frontend/middleware"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _authMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _loginMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		middleware.JwtMiddleware.LoginHandler,
	}
}

func _logoutMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.JwtMiddleware.LogoutHandler,
	}
}

func _registerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _adminMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _user0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _admin0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _setroleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _banMw() []app.HandlerFunc {
	// your code...
	return nil
}
