// Code generated by hertz generator.

package user

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _adminMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _user0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _admin0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _setroleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _banMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _banuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _user1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _resetpasswordMw() []app.HandlerFunc {
	// your code...
	return nil
}
